import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";
import { Col } from "react-bootstrap";
import Sidebar from "./components/sidebar/sidebar";

const inter = Montserrat({ 
  subsets: ["latin"],
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal', 'italic'],
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Currículo Cloves Duarte",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} style={{ display: "flex" }}>
        <Col md={3} style={{ position: "fixed" }}>
          <Sidebar/>
        </Col>
        {children}
      </body>
    </html>
  );
}
